---
- name: Install postgresql-11
  apt:
    name: postgresql-11
    state: present
- name: Install python3-psycopg2
  apt:
    name: python3-psycopg2
    state: present
- name: Create postgresql user
  postgresql_user:
    name: ejabberd
    password: ejabberd
  become_user: postgres
- name: Create postgresql db
  postgresql_db:
    name: ejabberd
    owner: ejabberd
  become_user: postgres
- name: Install ejabberd
  apt:
    deb: https://static.process-one.net/ejabberd/downloads/21.04/ejabberd_21.04-0_amd64.deb
- name: Check schema
  postgresql_query:
    db: ejabberd
    login_user: ejabberd
    query: "select count(*) as ts from pg_catalog.pg_tables where tableowner = 'ejabberd'"
  become_user: ejabberd
  register: schema_check
- name: Setup database
  postgresql_query:
    db: ejabberd
    login_user: ejabberd
    path_to_script: /opt/ejabberd-21.04/lib/ejabberd-21.04/priv/sql/pg.new.sql
    as_single_query: yes
  when: schema_check.query_result[0].ts != 41
  become_user: ejabberd
- name: setup ejabberd.service in systemd
  file:
    src: /opt/ejabberd-21.04/bin/ejabberd.service
    dest: /etc/systemd/system/ejabberd.service
    state: link
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Configure /opt/ejabberd/conf/ejabberd.yml
  template:
    src: ejabberd.yml.j2
    dest: /opt/ejabberd/conf/ejabberd.yml
  register: ejabberd_yml
- name: Setup ejabberd.service
  systemd:
    name: ejabberd
    enabled: yes
    state: started
- name: Restart ejabberd.service
  systemd:
    name: ejabberd
    enabled: yes
    state: restarted
  when: ejabberd_yml.changed
