---
- name: Install ejabberd
  apt:
    deb: https://static.process-one.net/ejabberd/downloads/21.04/ejabberd_21.04-0_amd64.deb
- name: setup ejabberd.service in systemd
  file:
    src: /opt/ejabberd-21.04/bin/ejabberd.service
    dest: /etc/systemd/system/ejabberd.service
    state: link
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Configure /opt/ejabberd/conf/ejabberd.yml
  template:
    src: ejabberd.yml.j2
    dest: /opt/ejabberd/conf/ejabberd.yml
  register: ejabberd_yml
- name: Setup ejabberd.service
  systemd:
    name: ejabberd
    enabled: yes
    state: started
- name: Restart ejabberd.service
  systemd:
    name: ejabberd
    enabled: yes
    state: restarted
  when: ejabberd_yml.changed
