- name: Set up certs
  hosts: 127.0.0.1
  connection: local

- name: Set up XMPP certs
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: obtain-certs
      vars:
        domain: "{{ xmpp_domain }}"
- name: Deploy XMPP certs
  hosts: frtcuop
  roles:
    - deploy-xmpp-certs
