- name: set DNS records
  community.aws.route53:
    state: present
    zone: "{{ dns_aws_zone }}"
    record: "{{ item.srv_record }}.{{ xmpp_domain }}"
    type: SRV
    value: "0 0 {{ item.port }} {{ hostvars['frtcuop'].ansible_host }}"
    wait: yes
    overwrite: yes
  loop:
    - { srv_record: '_xmpp-server._tcp', port: '5269' }
    - { srv_record: '_xmpp-client._tcp', port: '5222' }
    - { srv_record: '_stun._udp', port: '3478' }
    - { srv_record: '_stun._tcp', port: '3478' }
    - { srv_record: '_stuns._tcp', port: '5349' }
    - { srv_record: '_turn._udp', port: '3478' }
    - { srv_record: '_turn._tcp', port: '3478' }
    - { srv_record: '_turns._tcp', port: '5349' }
