- name: copy fullchain
  copy:
    src: "data/cert-{{ xmpp_domain }}-fullchain.crt"
    dest: /opt/ejabberd/conf/fullchain.pem
- name: copy privkey
  copy:
    src: "data/cert-{{ xmpp_domain }}.key"
    dest: /opt/ejabberd/conf//privkey.pem
- name: restart ejabberd.service
  systemd:
    name: ejabberd
    enabled: yes
    state: restarted
